apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-pod-quota
spec:
  replicas: 15
  selector:
    matchLabels:
      app: test-pod-quota
  template:
    metadata:
      labels:
        app: test-pod-quota
    spec:
      containers:
      - image: xian310/who-is-there:5
        name: test-pod-quota
      restartPolicy: Always
