---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pv-claim
  namespace: formation
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
