---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-nfs-pv
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 192.168.56.201
    path: /var/nfs-export
