#!/bin/bash

if [[ $(id -u) -ne 0 ]] ; then
  echo "You need to be root!"
  exit 1
fi

apt update
apt install nfs-kernel-server
systemctl status nfs-kernel-server
systemctl enable nfs-kernel-server
mkdir /var/nfs-export
echo "/var/nfs-export *(rw,sync,no_subtree_check,no_root_squash)"  > /etc/exports
exportfs -a
