#!/bin/bash

if [[ $(id -u) -ne 0 ]] ; then
  echo "You need to be root!"
  exit 1
fi

apt install nfs-common

# To manually check the mount:
# mkdir /mnt/nfs
# mount -t nfs NFS-SERVER-IP:/var/nfs-export /mnt/nfs/
