apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "namespace-resource-limits"
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "2"
        memory: "1G"
      min:
        cpu: "200m"
        memory: "6M"
    - type: "Container"
      max:
        cpu: "1"          # forbid container that have specified
        memory: "1G"      #   resources.limits bigger than those values
      min:                # forbid container that have specified
        cpu: "100m"       #   resources.requests smaller than those values
        memory: "4M"
      default:            # force the resources.limits if not specified
        cpu: "300m"
        memory: "200M"
      defaultRequest:     # fix the resources.requests if not specified
        cpu: "200m"
        memory: "100M"
      maxLimitRequestRatio:
        cpu: "10"
